### ISSUE TITLE
gaussian weights not (0,1) doc issue

### ISSUE THREAD

**Issue by vonGameTheory** [mlampros/elmNNRcpp#1]
documentation issue: it says "normal_gaussian" weights are (0,1) but they are gaussian normal negative/positive

**Comment by mlampros** [comment]
hi @vonGameTheory,

when specifying 'normal_gaussian' then the function calls the RcppArmadillo function [randn](https://github.com/mlampros/elmNNRcpp/blob/master/src/utils.cpp#L271) and based on the [Armadillo documentation](http://arma.sourceforge.net/docs.html#randu_randn_standalone)

```R

randn() uses a normal/Gaussian distribution with zero mean and unit variance 

```
I'll fix the documentation accordingly. Thanks.
