### ISSUE TITLE
OSELM or ORELM

### ISSUE THREAD

**Issue by athammad** [mlampros/elmNNRcpp#3]
Hi,

thank you for developing this amazing library. 
I was wandering if you have any plan to implement OSELM or (even better) [ORELM](https://github.com/chickenbestlover/Online-Recurrent-Extreme-Learning-Machine)?

Best wishes

**Comment by mlampros** [comment]
Hi @athammad,

I don't intend (currently) to port in R any of the OSELM or ORELM algorithms but once you've installed the python package you can use the [reticulate](https://github.com/rstudio/reticulate) package to load it from within R. I see that currently only the python 2 version is available (based on the [issue that you opened](https://github.com/chickenbestlover/Online-Recurrent-Extreme-Learning-Machine/issues/4) in the repository).
